-- +goose Up

CREATE TABLE clients (
	id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_client_user FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);


ALTER TABLE clients DROP COLUMN name, DROP COLUMN email;
ALTER TABLE clients ADD COLUMN first_name VARCHAR(255) NOT NULL;
ALTER TABLE clients ADD COLUMN last_name VARCHAR(255) NOT NULL;

-- +goose Down
DROP TABLE IF EXISTS clients;





CREATE TABLE freelancers (
    id INT PRIMARY KEY,
    first_name TEXT NULL,
    last_name TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_client_user FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);